Sprint1
ClevertecFrontendLab/sprint1-MuJlblii pull request #1
Opened 2023-01-28 17:25 UTC by MuJlblii

2023-01-28 17:48 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1674928107/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1674928107/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1674928107/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1674928107/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1674928107/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1674928107/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1674928107/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1674928107/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1674928107/content-window.png)

2023-01-28 18:00 UTC, dariavorom requested changes

2023-01-28 18:00 UTC, dariavorom commented on src/app/reducer.ts
> +// export interface IstateMainRedux {
удалить во всем файлам закомментированный код (его много)

2023-01-28 18:00 UTC, dariavorom commented on src/components/bookbar/bookbar.module.css
> +    /* width: 38px; */
в css файлах тоже убрать закомментированный

2023-01-28 18:00 UTC, dariavorom commented on src/components/bookbar/bookbar.tsx
> +                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
svg-код в компоненте выглядит так себе, плохая практика. лучше сразу импортировать svg. почитай об этом. у тебя будет что-то типа import { ReactComponent as Icon } from './assets/icon.svg'. и в коде выводишь <Icon />, так же будут доступны и пропсы

2023-01-28 18:00 UTC, dariavorom commented on src/components/bookshelf/bookcard/bookcard.tsx
> +    const star = (size?: string) => <svg width={size === 'small' ? '13' : '20'} height={size === 'small' ? '12' : '19'} viewBox="0 0 20 19" fill="none" xmlns="http://www.w3.org/2000/svg">
про svg написала выше

2023-01-29 15:01 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1675004479/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1675004479/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1675004479/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1675004479/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1675004479/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1675004479/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1675004479/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1675004479/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1675004479/content-window.png)

2023-01-29 15:14 UTC, dariavorom approved these changes

2023-01-29 15:14 UTC, dariavorom commented on src/components/bookbar/bookbar.tsx
> +                id='view1'
Надо назвать как-то читабельно, чтобы можно было сразу понять, о чем речь, какой вид: например, 'listView' или просто 'list' т.д. даже,  ещё лучше в enum вынести. Можно поправить со следующим спринтом

2023-01-29 15:14 UTC, dariavorom commented on src/components/bookshelf/bookcard/bookcard.tsx
> +      });
Добавить в зависимость пустой массив

2023-01-29 15:15 UTC, merged